version: "3.3"
services:
  db:
    container_name: db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vyapari
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - './db/mysql/data:/var/lib/mysql'
      - './db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './db/sql:/docker-entrypoint-initdb.d/:ro'
#    networks:
#      - local-net

# FastAPI
#  vyapari-backend:
#    links:
#      - db
#    container_name: vyapari-backend
#    build: .
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/home/app
#    networks:
#      - local-net
#
#networks:
#  local-net:
#    driver: bridge