---
common:
  dry_run: True

strategy: MomentumStrategy
adhoc_run: False

# Config for ORBStrategy
ORBStrategy:
  STOCK_MIN_PRICE: 20
  STOCK_MAX_PRICE: 1000
  MOVED_DAYS: 3
  BARSET_RECORDS: 30
  AMOUNT_PER_ORDER: 1000
  MAX_NUM_STOCKS: 40
  MAX_STOCK_WATCH_COUNT: 100
  TRAIL_PERCENT: 2.00

# Config for LWBreakout
LWBreakout:
  STOCK_MIN_PRICE: 20
  STOCK_MAX_PRICE: 1000
  MOVED_DAYS: 3
  BARSET_RECORDS: 30
  AMOUNT_PER_ORDER: 1000
  MAX_NUM_STOCKS: 40
  MAX_STOCK_WATCH_COUNT: 100

